language: php

dist: trusty
sudo: required

cache:
    apt: true
    directories:
        - vendor
        - bin

addons:
    hosts:
        - security-bundle.vlr.localtest

php:
    - 7.1

install:
    - composer self-update
    - composer install --dev --prefer-source

install:
    - git clone --branch trusty --depth=1 https://github.com/rezzza/travis-ci.git ~/.rezzza.travis-ci
    - ~/.rezzza.travis-ci/php/bootstrap.sh apcu fpm
    - phpenv rehash
    - ~/.rezzza.travis-ci/apache/bootstrap.sh 80
    - ln -s ~/build/rezzza/SecurityBundle/features/bootstrap ~/vhosts/security-bundle.vlr.localtest
    - composer install --optimize-autoloader --prefer-dist --no-scripts


script:
    - bin/atoum -ulr
    - bin/behat -f progress -vvv

